# Generated by Django 5.2.12 on 2026-03-19 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Workouts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userworkout',
            name='status',
            field=models.CharField(choices=[('saved', 'Saved'), ('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
